# ~/.config/starship.toml

# [aws]
# symbol = "îŒ½  "

# [conda]
# symbol = "ï„Œ "

# [dart]
# symbol = "î˜ "
# format = "via [$symbol]($style)"

# [directory]
# read_only = " ï ½"
# truncation_length = 1

# [docker_context]
# symbol = "ïŒˆ "

# [elixir]
# symbol = "î‰µ "
# format = 'via [$symbol]($style)'

# [elm]
# symbol = "î˜¬ "

# [git_branch]
# symbol = "ï˜ "

# [golang]
# symbol = "î˜§ "
# format = 'via [$symbol]($style)'

# [hg_branch]
# symbol = "ï˜ "

# [java]
# symbol = "î‰– "
# format = 'via [$symbol]($style)'

# [julia]
# symbol = "î˜¤ "

# [memory_usage]
# symbol = "ï¡š "

# [nim]
# symbol = "ïš¤ "

# [nix_shell]
# symbol = "ï‹œ "

# [nodejs]
# symbol = "îœ˜ "
# format = 'via [$symbol]($style)'

# [package]
# symbol = "ï£– "

# [perl]
# symbol = "î© "

# [php]
# symbol = "î˜ˆ "

# [python]
# symbol = "î˜† "
# format = 'via [$symbol]($style)'

# [ruby]
# symbol = "îˆ¾ "

# [rust]
# format = 'via [$symbol]($style)'

# [scala]
# symbol = "îœ· "

# [shlvl]
# symbol = "ï„  "

# [swift]
# symbol = "ï¯£ "
# format = 'via [$symbol]($style)'

# [git_status]
# disabled = true

# AF3A03 orange

format = """
[î‚¶](#010854)\
$username\
[î‚°](bg:#8800F2 fg:#010854)\
$directory\
[î‚°](fg:#8800F2 bg:#F2751C)\ 
$git_branch\
$git_status\
[î‚°](fg:#F2751C bg:#004B00)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[î‚°](fg:#004B00 bg:#06969A)\
$docker_context\
[î‚°](fg:#06969A bg:#076678)\
$time\
[î‚° ](fg:#076678)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "bg:#010854"
style_root = "bg:#010854"
format = '[ $user ğŸ€ ]($style)'

[directory]
style = "bg:#8800F2"
format = "[ $path ]($style)"
truncation_length = 2 #from 3
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[c]
symbol = "î˜ "
style = "bg:#004B00"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#F2751C"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = "î‰µ "
style = "bg:#004B00"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#004B00"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "ï˜"
style = "bg:#F2751C"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#F2751C"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#004B00"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "bg:#004B00"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:#004B00"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#004B00"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#004B00"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ïš¤ "
style = "bg:#004B00"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#004B00"
format = '[ $symbol ($version) ]($style)'


[php]
symbol = "î˜ˆ"
style = "bg:#004B00"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "î˜† "
style = "bg:#004B00"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%I:%M" # Hour:Minute Format
style = "bg:#076678"
format = '[ $time ğŸ€ ]($style)'
